rvm:
- 2.2

script:
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rake

deploy:
  provider: heroku
  api_key:
    secure: "kYJLlclvJF2o8GNf6yWHPeBn4DO9A+wXj3fxozY5wLhszYiJme2PNFOVGaQSUu0Dhz3sZwHVY7+BBanKH1fwroy6RX0daa8O7W/7c0ObgSQWBSfl5bH52aG1lDwiNYLYw17Ram3gr+ZAH6TEcI7ZlwjvTqbFH6yRexRPWB6b0IhBnS0a4cm8wrmHA2beaqkuhJrodKNSEdo23nYd5oBSofgUhfbOFeeQO8az3ZmY3hjzmf0Mnt1X2DNsDh9L12669VJPJ0W4ZG/ZgrKLOH1FqXhnn42uK04xcVPukxG4W2ctSts2VvZ2fpeWNNejjcXQm4hPRHOddLWEJoHTIeNFPcb7rJJ3OjDSpWBZ5eoCdCBSQELjV5um/TfDY08oNoRUHo5d6Dk3+g8anZj8/nEm7FRv4zV+L+KEYK3bujwwl6bXpsNPzwNK5vWrn1rSa1hfNTmAF44LNsvmkFfEeoRA8pUejzrzxcuKSf6MTPF7dHqk35fpJA5/BVF9ML0aqB6nCWgtWFEANuDMtSDW2/ocnbRzkhmZKZn+lze7PAnEryQKonir/f5dushbnfBKkrmUauShFx1ZZN7m+ISLIl1EjJ+SccB3+9kmF7uXILrxMqVJkamU89aZPJlujTADcarle0hgpY9AS/bWsDe36N0oedRspdiNc02i1l/2wbyX1OI="
  app: 'whispering-peak-6884'
  on:
    repo: dobryakov/snippet-shortener
    branch: master
  run:
    - "rake db:migrate"
  strategy: git

